"""Initial schema

Revision ID: f645f21e2af7
Revises: 
Create Date: 2026-01-12 16:55:55.599855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f645f21e2af7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('current_rev_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('blocks',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_block_id', sa.UUID(), nullable=True),
    sa.Column('order_key', sa.String(length=100), nullable=False),
    sa.Column('block_type', sa.Enum('paragraph', 'heading1', 'heading2', 'list', 'todo', 'code', 'quote', 'divider', name='blocktype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_index('idx_document_order', 'blocks', ['document_id', 'order_key'], unique=False)
    op.create_index('idx_document_parent', 'blocks', ['document_id', 'parent_block_id'], unique=False)
    op.create_table('document_acl',
    sa.Column('acl_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('acl_id')
    )
    op.create_index('idx_document_user', 'document_acl', ['document_id', 'user_id'], unique=True)
    op.create_table('revisions',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rev_number', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('client_batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index('idx_device_batch', 'revisions', ['device_id', 'client_batch_id'], unique=False)
    op.create_index('idx_document_rev', 'revisions', ['document_id', 'rev_number'], unique=False)
    op.create_table('share_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    op.create_table('ops',
    sa.Column('op_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('op_type', sa.Enum('insert_block', 'delete_block', 'move_block', 'update_text', 'update_props', name='operationtype'), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('op_id')
    )
    op.create_table('revision_snapshots',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('blocks_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('revision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_snapshots')
    op.drop_table('ops')
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('idx_document_rev', table_name='revisions')
    op.drop_index('idx_device_batch', table_name='revisions')
    op.drop_table('revisions')
    op.drop_index('idx_document_user', table_name='document_acl')
    op.drop_table('document_acl')
    op.drop_index('idx_document_parent', table_name='blocks')
    op.drop_index('idx_document_order', table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('documents')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
