"""remove_explicit_nullable_from_product_length_tolerance

Revision ID: 23f1d034f8bb
Revises: 2408d18b1a5e
Create Date: 2026-01-19 18:30:04.838052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f1d034f8bb'
down_revision = '2408d18b1a5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
