"""make_process_fields_nullable

Revision ID: 2408d18b1a5e
Revises: 79bc69ceff26
Create Date: 2026-01-19 18:28:26.978447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2408d18b1a5e'
down_revision = '79bc69ceff26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processes', 'material_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('processes', 'heat_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('processes', 'lot_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('processes', 'finished_size',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('processes', 'standard_customer',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('processes', 'standard_wst',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('processes', 'product_condition',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('processes', 'product_surface',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('processes', 'product_diameter_tolerance',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('processes', 'product_curvature_tolerance',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('processes', 'stock_size',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('processes', 'stock_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('processes', 'stock_no',
               existing_type=sa.VARCHAR(length=63),
               nullable=True)
    op.alter_column('processes', 'material_btt',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    op.alter_column('processes', 'material_btt_sym_tolerance',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
    op.alter_column('processes', 'remarks',
               existing_type=sa.VARCHAR(length=4095),
               nullable=True)
    op.alter_column('processes', 'current_rev_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('processes', 'preview_status',
               existing_type=postgresql.ENUM('empty', 'error', 'ok', 'ok_not_editable', name='preview_status_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processes', 'preview_status',
               existing_type=postgresql.ENUM('empty', 'error', 'ok', 'ok_not_editable', name='preview_status_enum'),
               nullable=False)
    op.alter_column('processes', 'current_rev_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('processes', 'remarks',
               existing_type=sa.VARCHAR(length=4095),
               nullable=False)
    op.alter_column('processes', 'material_btt_sym_tolerance',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
    op.alter_column('processes', 'material_btt',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
    op.alter_column('processes', 'stock_no',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('processes', 'stock_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('processes', 'stock_size',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('processes', 'product_curvature_tolerance',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('processes', 'product_diameter_tolerance',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('processes', 'product_surface',
               existing_type=sa.VARCHAR(length=63),
               nullable=False)
    op.alter_column('processes', 'product_condition',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.alter_column('processes', 'standard_wst',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('processes', 'standard_customer',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('processes', 'finished_size',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('processes', 'lot_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('processes', 'heat_no',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('processes', 'material_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('processes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
