"""Surface-mesh artifact storage for simulation-step inspection.

This module keeps heavy 3D payloads out of the hot `simulation_steps` list. Pre
writes meshes generated by the restored legacy Trimesh/STL path. Missing legacy
artifacts are a processing error, not a reason to synthesize replacement meshes.
Only compact references/summaries are intended to be saved back into
`simulation_steps.calculations`.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
import os
from typing import Any, Literal

from app.models.workflow_runtime import SimulationStep
from app.services.files.paths import build_operation_dir, get_local_runs_root, join_path
from app.services.files.storage import ensure_directory, write_json_file
from app.services.preprocessor.surface_mesh import SurfaceMesh, SurfaceMeshError


SurfaceKind = Literal["initial", "final"]
ArtifactFormat = Literal["json", "stl"]

SURFACE_ARTIFACT_VERSION = 1
SURFACE_DIRNAME = "surface"


@dataclass(frozen=True, slots=True)
class GeneratedSurfaceArtifacts:
    meshes: dict[SurfaceKind, SurfaceMesh]
    summary: dict[str, Any]


def ensure_surface_artifacts_for_step(
    step: SimulationStep,
    *,
    document_id: int,
    max_outline_points: int,
    force: bool = False,
) -> GeneratedSurfaceArtifacts:
    """Load Pre-generated JSON/STL artifacts for a compiled simulation step.

    `max_outline_points` and `force` are accepted for API compatibility with
    earlier builds, but this function intentionally never generates fallback
    geometry. If the legacy Pre artifact is absent or unreadable, the caller gets
    an explicit error.
    """

    _ = (document_id, max_outline_points, force)
    return _load_cached_surface_artifacts(step)


def write_surface_artifacts_for_compiled_meshes(
    step: SimulationStep,
    *,
    document_id: int,
    meshes: dict[SurfaceKind, SurfaceMesh],
    force: bool = True,
) -> GeneratedSurfaceArtifacts | None:
    """Persist legacy Pre-generated meshes as selected-step artifacts."""

    if not meshes:
        return None

    generated_at = datetime.now(timezone.utc).isoformat()
    artifact_root = _artifact_root(step)
    artifact_storage_error = _safe_ensure_directory(artifact_root)

    summary: dict[str, Any] = {
        "version": SURFACE_ARTIFACT_VERSION,
        "source": "legacy_preprocessor_trimesh",
        "document_id": document_id,
        "document_version_id": step.document_version_id,
        "document_operation_id": step.document_operation_id,
        "execution_order": step.execution_order,
        "generated_at": generated_at,
        "artifacts": {},
    }
    if artifact_storage_error is not None:
        summary["artifact_storage_error"] = artifact_storage_error
    for kind, mesh in meshes.items():
        summary["artifacts"][kind] = _write_artifact_files(
            step=step,
            kind=kind,
            mesh=mesh,
            raw_geometry=mesh.to_payload(),
            artifact_root=artifact_root,
            force=force,
        )

    return GeneratedSurfaceArtifacts(meshes=dict(meshes), summary=summary)


def surface_artifact_abs_path(step: SimulationStep, kind: SurfaceKind, artifact_format: ArtifactFormat) -> str:
    """Return the absolute artifact path for a step/kind/format pair."""

    extension = "json" if artifact_format == "json" else "stl"
    return join_path(_artifact_root(step), f"{kind}_surface.{extension}")


def _load_cached_surface_artifacts(step: SimulationStep) -> GeneratedSurfaceArtifacts:
    summary = (step.calculations or {}).get("surface_artifacts")
    if not isinstance(summary, dict):
        raise SurfaceMeshError(
            _artifact_error_prefix(step)
            + "Legacy 3D surface artifacts are missing. Run the Pre worker for this document before opening 3D preview."
        )
    source = summary.get("source")
    if source != "legacy_preprocessor_trimesh":
        raise SurfaceMeshError(
            _artifact_error_prefix(step)
            + f"Unsupported surface artifact source={source!r}. Hidden geometry fallback is disabled; "
            "the row must be compiled by the legacy Trimesh/STL Pre path."
        )
    artifacts = summary.get("artifacts")
    if not isinstance(artifacts, dict):
        raise SurfaceMeshError(
            _artifact_error_prefix(step)
            + "Legacy surface artifact metadata is malformed: missing 'artifacts' object."
        )

    errors: list[str] = []
    storage_error = summary.get("artifact_storage_error")
    if storage_error:
        errors.append(f"artifact storage error: {storage_error}")

    meshes: dict[SurfaceKind, SurfaceMesh] = {}
    for kind in ("initial", "final"):
        artifact = artifacts.get(kind)
        if not isinstance(artifact, dict):
            errors.append(f"{kind}: missing artifact metadata")
            continue
        write_errors = artifact.get("write_errors")
        if isinstance(write_errors, dict) and write_errors:
            errors.append(f"{kind}: artifact write errors: {write_errors}")
        json_path = surface_artifact_abs_path(step, kind, "json")
        if not os.path.isfile(json_path):
            errors.append(f"{kind}: JSON mesh artifact file is missing at {json_path}")
            continue
        try:
            with open(json_path, encoding="utf-8") as handle:
                meshes[kind] = SurfaceMesh.from_payload(json.load(handle))
        except Exception as exc:
            errors.append(f"{kind}: cannot read JSON mesh artifact at {json_path}: {type(exc).__name__}: {exc}")

    if errors:
        raise SurfaceMeshError(
            _artifact_error_prefix(step)
            + "Legacy surface artifacts are unavailable: "
            + "; ".join(errors)
        )
    if not meshes:
        raise SurfaceMeshError(
            _artifact_error_prefix(step)
            + "Legacy surface artifact metadata exists, but no initial/final mesh was loaded."
        )
    return GeneratedSurfaceArtifacts(meshes=meshes, summary=summary)


def _artifact_error_prefix(step: SimulationStep) -> str:
    return (
        f"document_operation_id={step.document_operation_id} "
        f"document_version_id={step.document_version_id} "
        f"execution_order={step.execution_order}: "
    )


def with_surface_artifact_urls(
    summary: dict[str, Any],
    *,
    document_id: int,
    document_operation_id: int,
) -> dict[str, Any]:
    """Add route URLs to an artifact summary without persisting API paths."""

    payload = json.loads(json.dumps(summary))
    artifacts = payload.get("artifacts")
    if not isinstance(artifacts, dict):
        return payload

    for kind, artifact in artifacts.items():
        if kind not in {"initial", "final"} or not isinstance(artifact, dict):
            continue
        files = artifact.get("files")
        if not isinstance(files, dict):
            continue
        for artifact_format, file_info in files.items():
            if artifact_format not in {"json", "stl"} or not isinstance(file_info, dict):
                continue
            file_info["url"] = (
                f"/documents/{document_id}/simulation-steps/{document_operation_id}"
                f"/surface/artifacts/{kind}/{artifact_format}"
            )

    return payload


def _write_artifact_files(
    *,
    step: SimulationStep,
    kind: SurfaceKind,
    mesh: SurfaceMesh,
    raw_geometry: dict[str, Any] | None,
    artifact_root: str,
    force: bool,
) -> dict[str, Any]:
    json_path = surface_artifact_abs_path(step, kind, "json")
    stl_path = surface_artifact_abs_path(step, kind, "stl")
    json_payload = mesh.to_payload()
    write_errors: dict[str, str] = {}

    try:
        if force or not os.path.isfile(json_path):
            write_json_file(json_path, json_payload)
    except OSError as exc:
        write_errors["json"] = str(exc)
    try:
        if force or not os.path.isfile(stl_path):
            with open(stl_path, "wb") as handle:
                handle.write(mesh.to_binary_stl(solid_name=f"forgelab_{kind}_{step.document_operation_id}"))
    except OSError as exc:
        write_errors["stl"] = str(exc)

    root = get_local_runs_root()
    payload = {
        "kind": kind,
        "geometry_hash": _geometry_hash(raw_geometry),
        "summary": {
            "vertex_count": len(mesh.vertices),
            "face_count": len(mesh.faces),
            "cross_section_point_count": mesh.cross_section_point_count,
            "surface_area_mm2": mesh.surface_area_mm2,
            "volume_mm3": mesh.volume_mm3,
            "bounds": mesh.bounds,
        },
        "files": {
            "json": _file_info(json_path, root),
            "stl": _file_info(stl_path, root),
        },
        "artifact_root": _relative_path(artifact_root, root),
    }
    if write_errors:
        payload["write_errors"] = write_errors
    return payload


def _safe_ensure_directory(path: str) -> str | None:
    try:
        ensure_directory(path)
        return None
    except OSError as exc:
        return str(exc)


def _artifact_root(step: SimulationStep) -> str:
    return join_path(
        build_operation_dir(get_local_runs_root(), step.document_version_id, step.execution_order),
        SURFACE_DIRNAME,
        f"document_operation_{step.document_operation_id}",
    )


def _file_info(path: str, root: str) -> dict[str, Any]:
    return {
        "relative_path": _relative_path(path, root),
        "size_bytes": os.path.getsize(path) if os.path.isfile(path) else 0,
    }


def _relative_path(path: str, root: str) -> str:
    try:
        return os.path.relpath(path, root)
    except ValueError:
        return path


def _geometry_hash(raw_geometry: dict[str, Any] | None) -> str | None:
    if raw_geometry is None:
        return None
    canonical = json.dumps(raw_geometry, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
